Violation:
  properties:
    access_duration:
      description: Specify the access duration for the new registered node.
      type: string
    actions:
      description: Actions
      items:
        description: Actions
        type: string
      type: array
    auto_enable:
      description: Specifies if a host can self remediate the violation (enable network
        button) or if they can not and must call the help desk.
      type: string
    button_text:
      description: Text displayed on the violation form to hosts.
      type: string
    delay_by:
      description: Delay before triggering the violation.
      properties:
        interval:
          description: Interval
          type: integer
        unit:
          description: Unit
          type: string
      type: object
    desc:
      description: Description
      type: string
    enabled:
      description: Enabled
      type: string
    external_command:
      description: External Command
      type: string
    grace:
      description: Amount of time before the violation can reoccur. This is useful
        to allow hosts time (in the example 2 minutes) to download tools to fix their
        issue, or shutoff their peer-to-peer application.
      properties:
        interval:
          description: Interval
          type: integer
        unit:
          description: Unit
          type: string
      type: object
    id:
      description: Use a number above 1500000 if you want to be able to delete this
        violation later.
      type: string
    max_enable:
      description: Number of times a host will be able to try and self remediate before
        they are locked out and have to call the help desk. This is useful for users
        who just <i>click through</i> violation pages.
      type: integer
    priority:
      description: Range 1-10, with 1 the higest priority and 10 the lowest. Higher
        priority violations will be addressed first if a host has more than one.
      type: string
    redirect_url:
      description: Destination URL where PacketFence will forward the device. By default
        it will use the Redirection URL from the connection profile configuration.
      type: string
    target_category:
      description: When selecting the <strong>role</strong> action, triggering the
        violation will change the node to this role.
      type: string
    template:
      description: HTML template the host will be redirected to while in violation.
        You can create new templates from the <em>Connection Profiles</em> configuration
        section.
      type: string
    trigger:
      description: Trigger
      type: string
    user_mail_message:
      description: A message that will be added to the e-mail sent to the user regarding
        this violation.
      type: string
    vclose:
      description: When selecting the <strong>close</strong> action, triggering the
        violation will close this violation. This is an experimental workflow for
        Mobile Device Management (MDM).
      type: string
    vlan:
      description: Destination Role where PacketFence should put the client when a
        violation of this type is open.
      type: string
    whitelisted_roles:
      description: Nodes with the selected roles won't be affected by a violation
        of this type.
      items:
        description: Nodes with the selected roles won't be affected by a violation
          of this type.
        type: string
      type: array
    window:
      description: Amount of time before a violation will be closed automatically.
        Instead of allowing people to reactivate the network, you may want to open
        a violation for a defined amount of time instead.
      properties:
        interval:
          description: Interval
          type: integer
        unit:
          description: Unit
          type: string
      type: object
    window_dynamic:
      description: Only works for accounting violations.  The violation will be opened
        according to the time you set in the accounting violation (ie. You have an
        accounting violation for 10GB/month.  If you bust the bandwidth after 3 days,
        the violation will open and the release date will be set for the last day
        of the current month).
      type: string
  required: []
  type: object
