DROP TABLE IF EXISTS switches;
CREATE TABLE switches (
  `id` varchar(255) NOT NULL,
  `type` varchar(255) NULL,
  `description` varchar(255) NOT NULL,
  `macSearchesMaxNb` varchar(255) NOT NULL,
  `macSearchesSleepInterval` varchar(255) NOT NULL,
  `mode` varchar(255) NOT NULL,
  `SNMPAuthPasswordRead` varchar(255) NULL,
  `SNMPAuthPasswordTrap` varchar(255) NULL,
  `SNMPAuthPasswordWrite` varchar(255) NULL,
  `SNMPAuthProtocolRead` varchar(255) NULL,
  `SNMPAuthProtocolTrap` varchar(255) NULL,
  `SNMPAuthProtocolWrite` varchar(255) NULL,
  `SNMPCommunityRead` varchar(255) NULL,
  `SNMPCommunityTrap` varchar(255) NULL,
  `SNMPCommunityWrite` varchar(255) NULL,
  `SNMPEngineID` varchar(255) NULL,
  `SNMPPrivPasswordRead` varchar(255) NULL,
  `SNMPPrivPasswordTrap` varchar(255) NULL,
  `SNMPPrivPasswordWrite` varchar(255) NULL,
  `SNMPPrivProtocolRead` varchar(255) NULL,
  `SNMPPrivProtocolTrap` varchar(255) NULL,
  `SNMPPrivProtocolWrite` varchar(255) NULL,
  `SNMPUserNameRead` varchar(255) NULL,
  `SNMPUserNameTrap` varchar(255) NULL,
  `SNMPUserNameWrite` varchar(255) NULL,
  `SNMPVersion` varchar(255) NULL,
  `SNMPVersionTrap` varchar(255) NULL,
  `cliEnablePwd` varchar(255) NULL,
  `cliPwd` varchar(255) NULL,
  `cliUser` varchar(255) NULL,
  `cliTransport` varchar(255) NULL,
  `wsPwd` varchar(255) NULL,
  `wsUser` varchar(255) NULL,
  `wsTransport` varchar(255) NULL,
  `radiusSecret` varchar(255) NULL,
  `controllerIp` varchar(255) NULL,
  `controllerPort` varchar(255) NULL,
  `uplink` varchar(255) NULL,
  `vlans` varchar(255) NULL,
  `access_lists` varchar(255) NULL,
  `VoIPEnabled` varchar(255) NULL,
  `roles` varchar(255) NULL,
  `inlineTrigger` varchar(255) NULL,
  `deauthMethod` varchar(255) NULL,
  `switchIp` varchar(255) NULL,
  `ip` varchar(255) NULL,
  `portalURL` varchar(255) NULL,
  `RoleMap` varchar(255) NULL,
  `VlanMap` varchar(255) NULL,
  `AccessListMap` varchar(255) NULL,
  `uplink_dynamic` varchar (255) NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB;
